### PR TITLE
ISSUE-79 Resolves Ditto Identity based on the build type.

### LINKED ISSUE #79: [Android] App does not work in debug mode
After setting up the credentials as defined in [the documentation](https://github.com/getditto/demoapp-chat/blob/a01db1af43527b93d1ac41a5232cecb2a2b24c98/Android/README.md#building-the-app).

Attempting to run the Android app in debug mode will cause the following error: 
```
... E  Ditto: The license failed verification. Obtain a valid license token at https://portal.ditto.live.
```

The setup process [configures Ditto](https://github.com/getditto/demoapp-chat/blob/52e473bf7d3d02ef87000998bed2bd78a3dd7a92/Android/app/src/main/java/live/dittolive/chat/SplashActivity.kt#L55) with `DittoIdentity.OfflinePlayground` while the portal documentation suggest the usage of `DittoIdentity.OnlinePlayground`

It would be nice if the app could resolve different identities depending on the build type.

### PR DESCRIPTION
**Pull request by anyercastillo**
Fixes #79 

The problem
-
The setup process [configures Ditto](https://github.com/getditto/demoapp-chat/blob/52e473bf7d3d02ef87000998bed2bd78a3dd7a92/Android/app/src/main/java/live/dittolive/chat/SplashActivity.kt#L55) with `DittoIdentity.OfflinePlayground` which **does not allow** developers to use the Online Playground.

The solution:
-
Resolves the Ditto Identity based on the build type.

### CODE REVIEW

**Comment by okdistribute** [comment]
Great idea

File: Android/app/src/main/java/live/dittolive/chat/SplashActivity.kt [hunk 1]
```diff
@@ -48,15 +48,39 @@ class SplashActivity : AppCompatActivity() {
...
+
+  /**
+   * Returns [DittoIdentity.OnlinePlayground] for Debug builds,
+   * [DittoIdentity.OfflinePlayground] otherwise.
+   */
+  private fun resolveIdentity(androidDependencies: DefaultAndroidDittoDependencies): DittoIdentity {
+    if (BuildConfig.DEBUG) return DittoIdentity.OnlinePlayground(
+      dependencies = androidDependencies,
+      appId = BuildConfig.DITTO_APP_ID,
+      token = BuildConfig.DITTO_LICENSE_TOKEN
```
Comment (texasRanger09) [inline Android/app/src/main/java/live/dittolive/chat/SplashActivity.kt:72]: The Playground token will need to be used here. `BuildConfig.DITTO_LICENSE_TOKEN` refers to the offline-only license token which is different from the Playground token.

Comment (anyercastillo) [reply Android/app/src/main/java/live/dittolive/chat/SplashActivity.kt:72]: @texasRanger09 I agree that `DITTO_LICENSE_TOKEN` is kind of confusing for the Online Playground.
Current configuration in gradle looks like:
```
debug {
            def credsFile = rootProject.file("secure\\debug_creds.properties")
            ...
            buildConfigField('String', 'DITTO_LICENSE_TOKEN', prop['DITTO_LICENSE_TOKEN'])
}
```

What do you think about making a change to something like:
```
debug {
            def credsFile = rootProject.file("secure\\debug_creds.properties")
            ...
            buildConfigField('String', 'DITTO_PLAYGROUND_TOKEN', prop['DITTO_PLAYGROUND_TOKEN'])
}
```

And of-course with the corresponding changes in the README.md

Comment (anyercastillo) [reply Android/app/src/main/java/live/dittolive/chat/SplashActivity.kt:72]: Actually I made a typo in the previous message.
We may want to have a generic `DITTO_TOKEN` for "debug" and "release" but the following properties on the credentials files.

`debug_creds.properties` 
DITTO_PLAYGROUND_TOKEN=...

`release_creds.properties` 
DITTO_LICENSE_TOKEN=...
 

**build.gradle**
```
debug {
            def credsFile = rootProject.file("secure\\debug_creds.properties")
            ...
            buildConfigField('String', 'DITTO_TOKEN', prop['DITTO_PLAYGROUND_TOKEN'])
}

debug {
            def credsFile = rootProject.file("secure\\release_creds.properties")
            ...
            buildConfigField('String', 'DITTO_TOKEN', prop['DITTO_LICENSE_TOKEN'])
}
```

Comment (texasRanger09) [reply Android/app/src/main/java/live/dittolive/chat/SplashActivity.kt:72]: That looks right. I opened an issue #82 to address the confusing environment variable names. The Android variable names should be updated to match the iOS naming convention.

Comment (anyercastillo) [reply Android/app/src/main/java/live/dittolive/chat/SplashActivity.kt:72]: Cool, I will implement the suggested changes.
Thank for the review.

Comment (texasRanger09) [reply Android/app/src/main/java/live/dittolive/chat/SplashActivity.kt:72]: > We may want to have a generic `DITTO_TOKEN` for "debug" and "release"

The `App Id` is needed for both online and offline playground. However, the online playground token is not needed when using the offline playground identity and the offline license token is not needed when using the online playground identity.

Comment (anyercastillo) [reply Android/app/src/main/java/live/dittolive/chat/SplashActivity.kt:72]: You are correct, `BuildConfig.DITTO_TOKEN` will be the name generated by the Android plugin at compile time, the value of this variable will be set based on the build type:

**debug** will use the env var `DITTO_PLAYGROUND_TOKEN` stored in file `secure\\debug_creds.properties`
**release** will use the env var `DITTO_LICENSE_TOKEN ` stored in file `secure\\release_creds.properties`

I think that once #82 is ready for implementation, then Android can make use of only one property file.

File: Android/app/build.gradle [hunk 2]
```diff
@@ -29,7 +29,7 @@ android {
             def prop = new Properties()
             prop.load(new FileInputStream(credsFile))
             buildConfigField('String', 'DITTO_APP_ID', prop['DITTO_APP_ID']) // always use single quotes here
-            buildConfigField('String', 'DITTO_OFFLINE_TOKEN', prop['DITTO_OFFLINE_TOKEN'])
+            buildConfigField('String', 'DITTO_PLAYGROUND_TOKEN', prop['DITTO_PLAYGROUND_TOKEN'])
```
Comment (texasRanger09) [inline Android/app/build.gradle:32]: May need to pull in the Offline Token still since it is referenced in the code. Without it, we would see `Unresolved reference: DITTO_OFFLINE_TOKEN`. And vice versa for the Playground Token in release build.

Comment (anyercastillo) [reply Android/app/build.gradle:32]: You are correct, `DITTO_OFFLINE_TOKEN` is used in the source code.

Comment (anyercastillo) [reply Android/app/build.gradle]: I will be adding a commit soon to address it.

**Review by texasRanger09 — APPROVED** [review]
LGTM
